theme = "catppuccin-mocha"
padding-x = 10
padding-y = [10, 10]

[renderer]
performance = "High"

# Using Slang shader filters.
#
# First, clone the slang-shaders repository from GitHub to your local machine.
#   git clone https://github.com/libretro/slang-shaders.git
#
# Then, set the path to the desired .slangp filter file(s) like below.
# Multiple filters can be applied by adding more paths to the list.
#
# filters = ["/home/username/code/slang-shaders/crt/crt-aperture.slangp"]
# filters = ["C:\\Users\\username\\code\\slang-shaders\\crt\\crt-blurPi-sharp.slangp"]

[fonts]
family = "JetBrainsMonoNL Nerd Font Mono"
size = 16
use-drawable-chars = false

[bindings]
keys = [
  # Force Control+Space to send NUL (\x00) which tmux expects.
  { key = "space", with = "control", esc = "\u0000" }
]

[window]
mode = "Maximized"

[platform]
macos.renderer.backend = "Metal"

linux.renderer.backend = "Vulkan"

windows.renderer.backend = "DX12"
windows.shell = { program = "wsl -d Ubuntu --cd ~", args = [] }
